In [25]:
import pandas as pd 
master_df = pd.read_csv("../data/processed/master_dataset.csv", low_memory=False)

In [24]:
# Columns to fill with 0
fill_zero_cols = [
    'Salaries And Wages', 'Earnings From Equity Interest', 
    'Loss Adjustment Expense', 'Policyholder Benefits Ceded', 
    'Policyholder Benefits Gross', 'Net Policyholder Benefits And Claims',
    'Write Off', 'Gain On Sale Of Ppe', 'Average Dilution Earnings',
    'Other Special Charges', 'Selling And Marketing Expense', 
    'Other Operating Expenses', 'Impairment Of Capital Assets',
    'Gain On Sale Of Business', 'Restructuring And Mergern Acquisition'
]

for col in fill_zero_cols:
    if col in master_df.columns:
        master_df[col] = master_df[col].fillna(0)

# Columns to fill with median
fill_median_cols = [
    'fiveYearAvgDividendYield', 'earningsQuarterlyGrowth', 'lastDividendValue',
    'lastDividendDate', 'debtToEquity', 'earningsGrowth', 'dividendDate',
    'Normalized EBITDA', 'Total Unusual Items', 'Total Unusual Items Excluding Goodwill',
    'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
    'Interest Income', 'Total Operating Income As Reported', 'Diluted Average Shares',
    'Basic Average Shares', 'Diluted EPS', 'Basic EPS', 'Minority Interests',
    'Net Income Discontinuous Operations', 'Earnings From Equity Interest Net Of Tax',
    'Other Non Operating Income Expenses', 'Special Income Charges',
    'Interest Income Non Operating', 'Operating Income', 'Operating Expense',
    'Research And Development', 'Selling General And Administration',
    'General And Administrative Expense', 'Other Gand A',
    'Depreciation Amortization Depletion Income Statement',
    'Depreciation And Amortization In Income Statement',
    'Amortization', 'Amortization Of Intangibles Income Statement', 'Gross Profit',
    'Cost Of Revenue'
]

for col in fill_median_cols:
    if col in master_df.columns:
        median_value = master_df[col].median()
        master_df[col] = master_df[col].fillna(median_value)

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,previousClose,...,bookValue,grossMargins,ebitdaMargins,operatingMargins,returnOnAssets,returnOnEquity,profitMargins,earningsGrowth,revenueGrowth,beta
0,MMM,2021-03-31 04:00:00+00:00,135.374320,135.716350,134.055052,134.494812,2902572,0.0,0.0,142.520,...,8.867,0.39915,0.24114,0.12408,0.07584,0.75501,0.13027,-0.199,0.02,1.131
1,MMM,2021-04-01 04:00:00+00:00,134.892660,135.360344,133.210433,134.508759,2274912,0.0,0.0,142.520,...,8.867,0.39915,0.24114,0.12408,0.07584,0.75501,0.13027,-0.199,0.02,1.131
2,MMM,2021-04-05 04:00:00+00:00,135.339409,136.777337,135.213769,136.093277,2347748,0.0,0.0,142.520,...,8.867,0.39915,0.24114,0.12408,0.07584,0.75501,0.13027,-0.199,0.02,1.131
3,MMM,2021-04-06 04:00:00+00:00,136.114227,136.540026,135.409225,136.002548,1761349,0.0,0.0,142.520,...,8.867,0.39915,0.24114,0.12408,0.07584,0.75501,0.13027,-0.199,0.02,1.131
4,MMM,2021-04-07 04:00:00+00:00,135.527876,136.358519,135.360351,136.079315,1795794,0.0,0.0,142.520,...,8.867,0.39915,0.24114,0.12408,0.07584,0.75501,0.13027,-0.199,0.02,1.131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12555,A,2026-03-25 04:00:00+00:00,115.889999,116.400002,111.739998,112.980003,1704500,0.0,0.0,111.755,...,24.436,0.52300,0.27898,0.22859,0.08533,0.19946,0.18259,-0.036,0.07,1.312
12556,A,2026-03-26 04:00:00+00:00,113.860001,114.519997,113.269997,113.480003,2561800,0.0,0.0,111.755,...,24.436,0.52300,0.27898,0.22859,0.08533,0.19946,0.18259,-0.036,0.07,1.312
12557,A,2026-03-27 04:00:00+00:00,113.529999,113.739998,109.900002,110.239998,1269900,0.0,0.0,111.755,...,24.436,0.52300,0.27898,0.22859,0.08533,0.19946,0.18259,-0.036,0.07,1.312
12558,A,2026-03-30 04:00:00+00:00,111.559998,112.970001,111.070000,112.010002,1372900,0.0,0.0,111.755,...,24.436,0.52300,0.27898,0.22859,0.08533,0.19946,0.18259,-0.036,0.07,1.312
12559,A,2026-03-31 04:00:00+00:00,112.550003,113.779999,111.894997,113.129997,431807,0.0,0.0,111.755,...,24.436,0.52300,0.27898,0.22859,0.08533,0.19946,0.18259,-0.036,0.07,1.312

In [27]:
# Ensure sorted
features_df = features_df.sort_values(by=['Ticker', 'Date']).reset_index(drop=True)

# -------------------------------
# 1. RETURNS
# -------------------------------

# Daily return
features_df['return_1d'] = features_df.groupby('Ticker')['Close'].pct_change()

# Multi-day returns
features_df['return_5d'] = features_df.groupby('Ticker')['Close'].pct_change(5)
features_df['return_10d'] = features_df.groupby('Ticker')['Close'].pct_change(10)
features_df['return_21d'] = features_df.groupby('Ticker')['Close'].pct_change(21)

# -------------------------------
# 2. MOVING AVERAGES
# -------------------------------

features_df['ma_5'] = features_df.groupby('Ticker')['Close'].rolling(5).mean().reset_index(level=0, drop=True)
features_df['ma_10'] = features_df.groupby('Ticker')['Close'].rolling(10).mean().reset_index(level=0, drop=True)
features_df['ma_21'] = features_df.groupby('Ticker')['Close'].rolling(21).mean().reset_index(level=0, drop=True)

# -------------------------------
# 3. PRICE RELATIVE TO MOVING AVERAGES (Momentum)
# -------------------------------

features_df['price_ma5_ratio'] = features_df['Close'] / features_df['ma_5']
features_df['price_ma10_ratio'] = features_df['Close'] / features_df['ma_10']
features_df['price_ma21_ratio'] = features_df['Close'] / features_df['ma_21']

# -------------------------------
# 4. VOLATILITY (Rolling Std of Returns)
# -------------------------------

features_df['vol_5'] = features_df.groupby('Ticker')['return_1d'].rolling(5).std().reset_index(level=0, drop=True)
features_df['vol_10'] = features_df.groupby('Ticker')['return_1d'].rolling(10).std().reset_index(level=0, drop=True)
features_df['vol_21'] = features_df.groupby('Ticker')['return_1d'].rolling(21).std().reset_index(level=0, drop=True)

# -------------------------------
# 5. PRICE RANGE FEATURES
# -------------------------------

features_df['daily_range'] = features_df['High'] - features_df['Low']
features_df['range_pct'] = (features_df['High'] - features_df['Low']) / features_df['Close']

# -------------------------------
# 6. MOMENTUM (Trend Strength)
# -------------------------------

features_df['momentum_5'] = features_df['Close'] - features_df['Close'].shift(5)
features_df['momentum_10'] = features_df['Close'] - features_df['Close'].shift(10)
features_df['momentum_21'] = features_df['Close'] - features_df['Close'].shift(21)

features_df['momentum_5_pct'] = features_df['Close'].pct_change(5)
features_df['momentum_10_pct'] = features_df['Close'].pct_change(10)
features_df['momentum_21_pct'] = features_df['Close'].pct_change(21)


# -------------------------------
# 7. 52-WEEK POSITION
# -------------------------------

features_df['52w_position'] = (
    (features_df['Close'] - features_df['fiftyTwoWeekLow']) /
    (features_df['fiftyTwoWeekHigh'] - features_df['fiftyTwoWeekLow'])
)

# -------------------------------
# 8. GAP (Open vs Previous Close)
# -------------------------------

features_df['gap'] = (features_df['Open'] - features_df['previousClose']) / features_df['previousClose']

# -------------------------------
# 9. Risk Adjusted Return
# -------------------------------

features_df['risk_adjusted_return'] = features_df['return_5d'] / features_df['vol_5']

# -------------------------------
# 10. CLEAN NaNs (after feature creation)
# -------------------------------

features_df = features_df.fillna(0)

In [28]:
# -------------------------------
# 11. VOLUME-BASED FEATURES
# -------------------------------

# Rolling average volume (trend in trading activity)
features_df['volume_avg_5'] = features_df.groupby('Ticker')['Volume'].rolling(5).mean().reset_index(level=0, drop=True)
features_df['volume_avg_10'] = features_df.groupby('Ticker')['Volume'].rolling(10).mean().reset_index(level=0, drop=True)
features_df['volume_avg_21'] = features_df.groupby('Ticker')['Volume'].rolling(21).mean().reset_index(level=0, drop=True)

# Rolling volume volatility
features_df['volume_vol_5'] = features_df.groupby('Ticker')['Volume'].rolling(5).std().reset_index(level=0, drop=True)
features_df['volume_vol_10'] = features_df.groupby('Ticker')['Volume'].rolling(10).std().reset_index(level=0, drop=True)
features_df['volume_vol_21'] = features_df.groupby('Ticker')['Volume'].rolling(21).std().reset_index(level=0, drop=True)

# Volume momentum (change in trading activity)
features_df['volume_momentum_5'] = features_df['Volume'] - features_df.groupby('Ticker')['Volume'].shift(5)
features_df['volume_momentum_10'] = features_df['Volume'] - features_df.groupby('Ticker')['Volume'].shift(10)
features_df['volume_momentum_21'] = features_df['Volume'] - features_df.groupby('Ticker')['Volume'].shift(21)

# Volume momentum percentage
features_df['volume_momentum_5_pct'] = features_df['Volume'].pct_change(5)
features_df['volume_momentum_10_pct'] = features_df['Volume'].pct_change(10)
features_df['volume_momentum_21_pct'] = features_df['Volume'].pct_change(21)


# -------------------------------
# 12. TREND / MOMENTUM INDICATORS
# -------------------------------

# Rolling moving averages of close (already done: ma_5/10/21)
# We can add EMA (exponential moving average) for faster trend detection
features_df['ema_5'] = features_df.groupby('Ticker')['Close'].transform(lambda x: x.ewm(span=5, adjust=False).mean())
features_df['ema_10'] = features_df.groupby('Ticker')['Close'].transform(lambda x: x.ewm(span=10, adjust=False).mean())
features_df['ema_21'] = features_df.groupby('Ticker')['Close'].transform(lambda x: x.ewm(span=21, adjust=False).mean())

# MACD (12- and 26-day EMAs) and signal line
features_df['ema_12'] = features_df.groupby('Ticker')['Close'].transform(lambda x: x.ewm(span=12, adjust=False).mean())
features_df['ema_26'] = features_df.groupby('Ticker')['Close'].transform(lambda x: x.ewm(span=26, adjust=False).mean())
features_df['macd'] = features_df['ema_12'] - features_df['ema_26']
features_df['macd_signal'] = features_df.groupby('Ticker')['macd'].transform(lambda x: x.ewm(span=9, adjust=False).mean())

# RSI (Relative Strength Index)
def compute_rsi(series, period=14):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=period).mean()
    avg_loss = loss.rolling(window=period).mean()
    rs = avg_gain / (avg_loss + 1e-9)  # avoid division by 0
    rsi = 100 - (100 / (1 + rs))
    return rsi

features_df['rsi_14'] = features_df.groupby('Ticker')['Close'].transform(lambda x: compute_rsi(x, 14))


# -------------------------------
# 13. PRICE / VOLUME RATIOS & RELATIVES
# -------------------------------

# Price relative to EMA (trend confirmation)
features_df['close_ema5_ratio'] = features_df['Close'] / features_df['ema_5']
features_df['close_ema10_ratio'] = features_df['Close'] / features_df['ema_10']
features_df['close_ema21_ratio'] = features_df['Close'] / features_df['ema_21']

# Volume/price relative features
features_df['volume_price_ratio'] = features_df['Volume'] / (features_df['Close'] + 1e-9)
features_df['volume_ma5_ratio'] = features_df['Volume'] / (features_df['volume_avg_5'] + 1e-9)
features_df['volume_ma10_ratio'] = features_df['Volume'] / (features_df['volume_avg_10'] + 1e-9)
features_df['volume_ma21_ratio'] = features_df['Volume'] / (features_df['volume_avg_21'] + 1e-9)


# -------------------------------
# 14. CLEAN NaNs
# -------------------------------
features_df = features_df.fillna(0)
features_df

,Ticker,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,previousClose,...,macd,macd_signal,rsi_14,close_ema5_ratio,close_ema10_ratio,close_ema21_ratio,volume_price_ratio,volume_ma5_ratio,volume_ma10_ratio,volume_ma21_ratio
0,A,2021-03-31 04:00:00+00:00,121.724516,124.169637,121.724516,122.874596,1815500,0.000,0.0,111.755,...,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,14775.226649,0.000000,0.000000,0.000000
1,A,2021-04-01 04:00:00+00:00,123.705733,123.995671,122.748949,123.406136,1126400,0.000,0.0,111.755,...,0.042402,0.008480,0.000000,1.002880,1.003537,1.003931,9127.585066,0.000000,0.000000,0.000000
2,A,2021-04-05 04:00:00+00:00,124.861889,126.420244,124.861889,125.829811,1096300,0.194,0.0,111.755,...,0.268481,0.060481,0.000000,1.014938,1.018939,1.021452,8712.561757,0.000000,0.000000,0.000000
3,A,2021-04-06 04:00:00+00:00,126.381531,127.630144,125.703975,126.836441,1623200,0.000,0.0,111.755,...,0.522851,0.152955,0.000000,1.015255,1.022057,1.026858,12797.583933,0.000000,0.000000,0.000000
4,A,2021-04-07 04:00:00+00:00,126.071791,126.381533,124.406965,125.190979,954600,0.000,0.0,111.755,...,0.584922,0.239348,0.000000,1.001388,1.007186,1.012291,7625.150051,0.721433,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12555,MMM,2026-03-25 04:00:00+00:00,148.479996,149.169998,146.470001,148.050003,2238500,0.000,0.0,142.520,...,-4.632453,-4.275562,37.568553,1.009850,1.000829,0.974214,15119.891617,0.523601,0.499373,0.501642
12556,MMM,2026-03-26 04:00:00+00:00,147.089996,147.399994,143.710007,143.990005,2812100,0.000,0.0,142.520,...,-4.666050,-4.353660,36.179581,0.988033,0.978117,0.952042,19529.827715,0.706125,0.670261,0.631368
12557,MMM,2026-03-27 04:00:00+00:00,143.690002,146.190002,142.660004,143.039993,3428000,0.000,0.0,142.520,...,-4.714984,-4.425925,37.082695,0.987600,0.976695,0.950447,23965.325509,1.042604,0.828568,0.770029
12558,MMM,2026-03-30 04:00:00+00:00,143.699997,143.910004,141.759995,142.520004,2482900,0.000,0.0,142.520,...,-4.741070,-4.488954,28.888902,0.989283,0.977920,0.951577,17421.414016,0.886877,0.640735,0.575486
12559,MMM,2026-03-31 04:00:00+00:00,144.410004,144.529999,141.779999,142.755005,621746,0.000,0.0,142.520,...,-4.688733,-4.528910,29.516598,0.993924,0.983191,0.957224,4355.335916,0.268382,0.177843,0.149663